---
title: "Controllexperient"
output:
  html_document:
    df_print: paged
---

# Read and preprocess Control-data
```{r,echo=T, message=FALSE, warning=FALSE, r,echo=T}
if (!require("pacman")) install.packages("pacman")
library(pacman)
p_load(tidyverse)
p_load(R.utils)
sourceDirectory("./source/")
data<-readControl()  %>% preproControl() 

```

## check Accuracy

```{r echo=TRUE}
library(dplyr)
library(sjPlot)
group_by(data,kategory,session) %>% 
  summarize(mean_corr= mean(corrResp),sd_corr=sd(corrResp),mean_RT=mean(rtResp),sd_RT=sd(rtResp))
p <- ggplot(data=data, 
             aes(x = corrResp, y =rtResp, color= inSet) )+geom_point()
p+facet_grid(kategory  ~  session,margins = T)


fit_corrResp<-lm(corrResp~session*kategory,data = data)
aov(fit_corrResp)
sjp.lm(fit = fit_corrResp)

fit_corrRespset<-lm(corrResp~inSet*kategory,data = data)
summary(fit_corrRespset)
sjp.int(fit = fit_corrRespset, type = "eff")

fit_rtResp<-lm(rtResp~session*kategory,data = data)
aov(fit_rtResp)
sjp.lm(fit = fit_rtResp)

```

